### PR TITLE
Adding Demo Code Schema 

### PR DESCRIPTION
**Pull request by IliyanAng**
- Adding Demo Code Schema class to handle the demo code instances.
**NOTE:** This could improve readability and adds room for future extension of the DemoCodeProvider
- Fixing slight style cop error for public before private properties.
- Removing unnecessary using in the DemoCodeProvider class

### CODE REVIEW

**Comment by KristianMariyanov** [comment]
@IliyanAng Thank you for the effort.
Currently, I don't see this change as valuable. This is a temporary code which will be removed after we implement saving of snippets. We want to keep it as tight as we can. 
In the best case, when we implement saving snippets, we will only change how we get the code in the `DemoCodeProvider`.

**Comment by KristianMariyanov** [comment]
@IliyanAng Something which will be really beneficial for the project is integrating some kind of highlight library for the `/getting-started` page. Currently, we are using images because we don't have enough time to do it properly. 

If you want, you can integrate something like highlight-js (I didn't research a lot, but I saw that Microsoft use it for their docs) and change the images with the actual text.

**Comment by IliyanAng** [comment]
@KristianMariyanov  Sorry for the delay in my response!
I'll take a stab at it : ) 

**NOTE:** Due to the increased volume at my work and me pulling some overtimes, i can't provide a good time frame of when the PR will be ready. 
Apologies if it's a time sensitive matter.

**Comment by KristianMariyanov** [comment]
@IliyanAng You don't need to take responsibilities that you will do something. I just give some ideas if you want to tackle something in the project. We are all doing this for fun. If you have to estimate it, it's not fun anymore 😆

**Pull request closed without merging**
